##########################################################################################################################
# File automatically-generated by tool: [projectgenerator] version: [4.8.0-B50] date: [Sun Jan 18 15:38:47 CST 2026] 
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#	2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------

######################################
# target
######################################
TARGET = WB09_Blinky


######################################
# building variables
######################################
# debug build?
DEBUG = 1
# optimization
OPT = -Og


#######################################
# paths
#######################################
# Build path
BUILD_DIR = build

######################################
# source
######################################
# C sources
C_SOURCES =  \
Core/Src/main.c \
Core/Src/stm32wb0x_it.c \
Core/Src/stm32wb0x_hal_msp.c \
Drivers/BSP/STM32WB0x-nucleo/stm32wb0x_nucleo.c \
Drivers/STM32WB0x_HAL_Driver/Src/stm32wb0x_hal_cortex.c \
Drivers/STM32WB0x_HAL_Driver/Src/stm32wb0x_hal_rcc.c \
Drivers/STM32WB0x_HAL_Driver/Src/stm32wb0x_hal_rcc_ex.c \
Drivers/STM32WB0x_HAL_Driver/Src/stm32wb0x_hal_flash.c \
Drivers/STM32WB0x_HAL_Driver/Src/stm32wb0x_hal_flash_ex.c \
Drivers/STM32WB0x_HAL_Driver/Src/stm32wb0x_hal_gpio.c \
Drivers/STM32WB0x_HAL_Driver/Src/stm32wb0x_hal_dma.c \
Drivers/STM32WB0x_HAL_Driver/Src/stm32wb0x_hal_pwr.c \
Drivers/STM32WB0x_HAL_Driver/Src/stm32wb0x_hal_pwr_ex.c \
Drivers/STM32WB0x_HAL_Driver/Src/stm32wb0x_hal.c \
Drivers/STM32WB0x_HAL_Driver/Src/stm32wb0x_hal_usart.c \
Drivers/STM32WB0x_HAL_Driver/Src/stm32wb0x_hal_usart_ex.c \
Drivers/STM32WB0x_HAL_Driver/Src/stm32wb0x_hal_uart_ex.c \
Drivers/STM32WB0x_HAL_Driver/Src/stm32wb0x_hal_uart.c \
Core/Src/system_stm32wb0x.c \
Core/Src/sysmem.c \
Core/Src/syscalls.c \
Drivers/STM32WB0x_HAL_Driver/Src/stm32wb0x_hal_adc.c \
Drivers/STM32WB0x_HAL_Driver/Src/stm32wb0x_hal_pka.c \
Drivers/STM32WB0x_HAL_Driver/Src/stm32wb0x_hal_radio.c \
Drivers/STM32WB0x_HAL_Driver/Src/stm32wb0x_hal_radio_timer.c \
Drivers/STM32WB0x_HAL_Driver/Src/stm32wb0x_hal_rng.c \
Middlewares/ST/STM32_BLE/evt_handler/src/ble_evt.c \
Middlewares/ST/STM32_BLE/stack/config/ble_stack_user_cfg.c \
Core/Src/app_ble.c \
Core/Src/bleplat.c \
Core/Src/pka_manager.c \
Core/Src/hw_aes.c \
Core/Src/hw_rng.c \
Core/Src/bleplat_cntr.c \
Core/Src/miscutil.c \
Core/Src/osal.c \
Core/Src/RADIO_utils.c \
Core/Src/stm32wb0x_ll_adc.c \
Core/Src/stm32wb0x_ll_dma.c \
Core/Src/stm32wb0x_ll_gpio.c \
Core/Src/stm32wb0x_ll_pwr.c \
Core/Src/stm32wb0x_ll_rcc.c \
Core/Src/stm32wb0x_ll_rng.c \
Core/Src/stm32wb0x_ll_system.c \
Core/Src/stm32wb0x_ll_usart.c \
Core/Src/stm32wb0x_ll_utils.c

# ASM sources
ASM_SOURCES =  \
startup_stm32wb09.s \
Core/Src/blue_unit_conversion.s

# ASMM sources
ASMM_SOURCES = 



#######################################
# binaries
#######################################
PREFIX = arm-none-eabi-
# The gcc compiler bin path can be either defined in make command via GCC_PATH variable (> make GCC_PATH=xxx)
# either it can be added to the PATH environment variable.
ifdef GCC_PATH
CC = $(GCC_PATH)/$(PREFIX)gcc
AS = $(GCC_PATH)/$(PREFIX)gcc -x assembler-with-cpp
CP = $(GCC_PATH)/$(PREFIX)objcopy
SZ = $(GCC_PATH)/$(PREFIX)size
else
CC = $(PREFIX)gcc
AS = $(PREFIX)gcc -x assembler-with-cpp
CP = $(PREFIX)objcopy
SZ = $(PREFIX)size
endif
HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S
 
#######################################
# CFLAGS
#######################################
# cpu
CPU = -mcpu=cortex-m0plus

# fpu
# NONE for Cortex-M0/M0+/M3

# float-abi


# mcu
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)

# macros for gcc
# AS defines
AS_DEFS = 

# C defines
C_DEFS =  \
-DUSE_NUCLEO_32 \
-DUSE_HAL_DRIVER \
-DSTM32WB09


# AS includes
AS_INCLUDES = 

# C includes
C_INCLUDES =  \
-ICore/Inc \
-IDrivers/STM32WB0x_HAL_Driver/Inc \
-IDrivers/STM32WB0x_HAL_Driver/Inc/Legacy \
-IDrivers/BSP/STM32WB0x-nucleo \
-IDrivers/CMSIS/Device/ST/STM32WB0X/Include \
-IDrivers/CMSIS/Include \
-IMiddlewares/ST/STM32_BLE \
-IMiddlewares/ST/STM32_BLE/stack/include \
-IMiddlewares/ST/STM32_BLE/evt_handler/inc \
-IMiddlewares/ST/STM32_BLE/cryptolib/Inc


# compile gcc flags
ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

CFLAGS += $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

ifeq ($(DEBUG), 1)
CFLAGS += -g -gdwarf-2
endif


# Generate dependency information
CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"


#######################################
# LDFLAGS
#######################################
# link script
LDSCRIPT = stm32wb09_flash.ld

# libraries
LIBS = -lc -lm -lnosys -l:stm32wb0x_ble_stack.a -lcrypto
LIBDIR = -LMiddlewares/ST/STM32_BLE/stack/lib -LMiddlewares/ST/STM32_BLE/cryptolib 
LDFLAGS = $(MCU) -specs=nano.specs -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref -Wl,--gc-sections

# default action: build all
all: $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).hex $(BUILD_DIR)/$(TARGET).bin


#######################################
# build the application
#######################################
# list of objects
OBJECTS = $(addprefix $(BUILD_DIR)/,$(notdir $(C_SOURCES:.c=.o)))
vpath %.c $(sort $(dir $(C_SOURCES)))
# list of ASM program objects
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASM_SOURCES:.s=.o)))
vpath %.s $(sort $(dir $(ASM_SOURCES)))
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASMM_SOURCES:.S=.o)))
vpath %.S $(sort $(dir $(ASMM_SOURCES)))

$(BUILD_DIR)/%.o: %.c Makefile | $(BUILD_DIR) 
	$(CC) -c $(CFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.c=.lst)) $< -o $@

$(BUILD_DIR)/%.o: %.s Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@
$(BUILD_DIR)/%.o: %.S Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS) Makefile
	$(CC) $(OBJECTS) $(LDFLAGS) -o $@
	$(SZ) $@

$(BUILD_DIR)/%.hex: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(HEX) $< $@
	
$(BUILD_DIR)/%.bin: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(BIN) $< $@	
	
$(BUILD_DIR):
	mkdir $@		

#######################################
# clean up
#######################################
clean:
	-rm -fR $(BUILD_DIR)
  
#######################################
# dependencies
#######################################
-include $(wildcard $(BUILD_DIR)/*.d)



#######################################
# Flashing configurations
#######################################
STM32_PROG = /home/soda/STMicroelectronics/STM32Cube/STM32CubeProgrammer/bin/STM32_Programmer_CLI

flash: all
	@echo "Flashing via STM32CubeProgrammer..."
	$(STM32_PROG) -c port=SWD -w build/WB09_Blinky.bin 0x10040000 -v -rst
	@echo "Done!"

qflash:
	@go build -o flash_tool flash_wrapper.go
	@./flash_tool



# *** EOF ***


